#!/bin/sh

. "$HOME/.config/yadm/util.sh"

brew_install() {
  if ! brew list $@ 1>/dev/null 2>&1; then
    brew install $@
  fi
}

# Install required packages
if [ "$SYSTEM_TYPE" = "Darwin" ]; then
  log_info "Install packages"
  packages=$(cat $CONFIG/packages.brew $CONFIG/*/packages $CONFIG/*/packages.brew | sort -u)
  log_info "Packages: $(echo $packages)"
  for package in $packages; do
    brew_install $package
  done

  log_info "Install casks"
  casks=$(cat $CONFIG/packages.cask | sort -u)
  log_info "Casks: $(echo $casks)"
  for cask in $casks; do
    brew_install --cask $cask
  done
else
  packages=$(cat $CONFIG/packages.apt $CONFIG/*/packages $CONFIG/*/packages.apt | sort -u)
  log_info "Packages: $(echo $packages)"
  apt install -y $packages
fi

echo

# Installers
for installer in $CONFIG/*/install.sh; do
  log_info "Running $installer"
  $installer
  echo
done
