## Bedroom lights
- alias: Turn lights on when sun sets if I'm home
  trigger:
    platform: sun
    event: sunset
    offset: '-01:00:00'
  condition:
    - condition: state
      entity_id: device_tracker.marknexus
      state: 'home'
  action:
    - service: homeassistant.turn_on
      entity_id: group.bedroom_lights
    - service: notify.pushover
      data:
        message: Lights turned on before sunset

- alias: Turn lights on when I arrive home after sunset
  trigger:
    platform: state
    entity_id: device_tracker.marknexus
    from: 'not_home'
    state: 'home'
  condition:
    - condition: sun
      after: 'sunset'
      after_offset: '-01:00:00'
  action:
    - service: homeassistant.turn_on
      entity_id: group.bedroom_lights
    - service: notify.pushover
      data:
        message: Lights turned on due to return

- alias: Turn lights off when I leave
  trigger:
    platform: state
    entity_id: device_tracker.marknexus
    from: 'home'
    state: 'not_home'
  action:
    - service: homeassistant.turn_off
      entity_id: group.bedroom_lights
    - service: notify.pushover
      data:
        message: Lights turned off in absentia

## Waking up for work
- alias: Turn lights on when I'm up for work
  trigger:
    platform: time
    after: '07:15:00'
  condition:
    - condition: time
      weekday:
        - mon
        - tue
        - wed
        - thu
        - fri
  action:
    - service: homeassistant.turn_on
      entity_id: group.bedroom_lights

- alias: Turn heater on before I get up for work
  trigger:
    platform: time
    after: '06:50:00'
  condition:
    - condition: time
      weekday:
        - mon
        - tue
        - wed
        - thu
        - fri
  action:
    - service: homeassistant.turn_on
      entity_id: switch.heater

- alias: Turn heater off after I get up for work
  trigger:
    platform: time
    after: '07:10:00'
  condition:
    - condition: time
      weekday:
        - mon
        - tue
        - wed
        - thu
        - fri
  action:
    - service: homeassistant.turn_off
      entity_id: switch.heater
