- alias: Turn lights on when sun sets
  trigger:
    platform: sun
    event: sunset
    offset: '-01:30:00'
  action:
    - service: light.turn_on
      entity_id: group.bedroom
    - service: notify.pushover
      data:
        message: Lights turned on before sunset
