# vemek ~/.bashrc
#

# If not running interactively, don't do anything
[ -z "$PS1" ] && return

# Don't add dupe lines or lines beginning with spaces to history file
export HISTCONTROL=ignoreboth
export HISTSIZE=100000

# check the window size after each command and, if necessary,
# update the values of LINES and COLUMNS.
shopt -s checkwinsize

# make less more friendly for non-text input files, see lesspipe(1)
[ -x /usr/bin/lesspipe ] && eval "$(SHELL=/bin/sh lesspipe)"


PS1='\[\033[01;37m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]\$ '

##
# Source external config
#

if [ -f /etc/bash_completion ]; then
  . /etc/bash_completion
fi

if [ -f ~/.config/yadm/bash/aliases ]; then
  source ~/.config/yadm/bash/aliases
fi

if [ -f "$HOME/src/util/bash-git-prompt/gitprompt.sh" ]; then
  gitprompt_src="$HOME/src/util/bash-git-prompt/gitprompt.sh"
  GIT_PROMPT_THEME=Solarized
  GIT_PROMPT_ONLY_IN_REPO=1
  GIT_PROMPT_FETCH_REMOTE_STATUS=0
  GIT_PROMPT_START=$PS1
  GIT_PROMPT_END="$ "
  source "$gitprompt_src"
fi

if [ -d "$HOME/src/util/dircolors-solarized" ]; then
  eval $(dircolors "$HOME/src/util/dircolors-solarized/dircolors.256dark")
fi

[ -f ~/.fzf.bash ] && source ~/.fzf.bash
